# Generated by Django 4.1.7 on 2023-03-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dawa', '0004_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isssued_quantity',
            new_name='issued_quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
    ]
