# Generated by Django 4.1.7 on 2023-04-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawa', '0005_rename_isssued_quantity_product_issued_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recieved_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
